[MST-567] Allow decoding of query string in IDV flow
edx/frontend-app-account pull request #360
Opened 2020-12-10 20:26 UTC by bseverino

[MST-567](https://openedx.atlassian.net/browse/MST-567)

Related to https://github.com/edx/edx-platform/pull/25845

This addition decodes the `course_id` query string passed into the IDV flow, allowing special characters like `+`.

2020-12-11 15:39 UTC, schenedx requested changes
Is there a way to unit test this?
For example, after mounting this jsx, check in the sessionStorage?

2020-12-11 15:39 UTC, schenedx commented on src/id-verification/IdVerificationPage.jsx
> +        interpretNumericEntities: true
Why do we need this flag?

2020-12-11 15:41 UTC, bseverino commented
@schenedx Thanks for reminding me, I was going to see if there was a way I could do that. I'll work on that now.

2020-12-11 15:43 UTC, bseverino commented on src/id-verification/IdVerificationPage.jsx
> +        interpretNumericEntities: true
This is needed to convert the encoded query string, IE `course-v1%3AedX%2BDemoX%2BDemo_Course` is decoded back into `course-v1:edX+DemoX+Demo_Course`

2020-12-14 16:31 UTC, schenedx approved these changes
👍

2020-12-14 16:40 UTC, merged