docs: update README with environment variable details.
edx/frontend-app-account pull request #436
Opened 2021-05-21 20:08 UTC by davidjoy

2021-05-24 15:36 UTC, sarina requested changes

2021-05-24 15:36 UTC, sarina commented on README.rst
> +Please tag **@edx/community-engineering** on any PRs or issues.  Thanks!
🙏

2021-05-24 15:36 UTC, sarina commented on README.rst
> +* ``SUPPORT_URL`` - The fully-qualified
the fully qualified what?

2021-05-26 13:23 UTC, davidjoy commented on README.rst
> +* ``SUPPORT_URL`` - The fully-qualified
What the... wow.  Okay.  Uh.  Good job, me.

2021-05-26 13:31 UTC, sarina approved these changes

2021-05-26 17:41 UTC, merged