[MST-803] Add name change modal
edx/frontend-app-account pull request #486
Opened 2021-08-27 22:04 UTC by bseverino

[MST-803](https://openedx.atlassian.net/browse/MST-803)

If name change requires ID verification, display a modal that prompts the user to enter their ID name. On submit, this creates a pending name change + a verified name with the given names, and directs the user to the IDV flow.

![Screen Shot 2021-08-31 at 11 21 58 AM](https://user-images.githubusercontent.com/10442143/131535737-9fbfa5ca-3d8d-48a5-a826-ccd3324e558d.png)
![Screen Shot 2021-08-31 at 11 22 12 AM](https://user-images.githubusercontent.com/10442143/131535746-a13c2adf-b40c-4951-a446-88a2f0c995e3.png)
![Screen Shot 2021-08-31 at 11 22 22 AM](https://user-images.githubusercontent.com/10442143/131535752-60b8edf5-56ee-4ba8-9ddd-3c58dd0e53eb.png)
![Screen Shot 2021-08-31 at 11 22 31 AM](https://user-images.githubusercontent.com/10442143/131535758-6453e885-4923-4f20-a06e-efcc458b9973.png)

2021-09-01 19:15 UTC, bseverino commented
@alangsto I created two new tickets to address those suggestions:

[MST-1028: Validate user input for verified name](https://openedx.atlassian.net/browse/MST-1028)
[MST-1029: Direct the user to IDV after saving a new verified name](https://openedx.atlassian.net/browse/MST-1029)

Though this is behind the waffle flag, I think I'll wait to merge this until MST-1028 is complete.

2021-09-03 12:56 UTC, MichaelRoytman requested changes

2021-09-07 15:20 UTC, schenedx approved these changes
👍

2021-09-07 15:20 UTC, schenedx commented on src/account-settings/AccountSettingsPage.jsx
> +      && this.props.formErrors.name === 'This name change requires ID verification.'
#NIT Should we have a shorter name than this? Feels kinda long for a value to be checking against.

2021-09-07 15:20 UTC, schenedx commented on src/account-settings/name-change/data/reducers.js
> +          errors: action.payload.errors || { general_error: 'Something went wrong. Please try again.' },
#NIT Instead of `Something went wrong`, Why not just say, `There were technical errors prevented the name change. You can try again to see if the error can go away`? Or something along that line?

2021-09-08 13:25 UTC, bseverino commented on src/account-settings/name-change-modal/NameChangeModal.jsx
> +    setVerifiedName('');
I opted to keep this as a local value, as hooking it up to the form values would clear the errors and reset the modal on edit. I renamed it to `verifiedNameInput` so it's a little clearer that it's local to this component.

2021-09-08 13:27 UTC, bseverino commented on src/account-settings/name-change-modal/NameChangeModal.jsx
> +      await postNameChange(formValues.name)
I created a separate saga for this component including both the name change request and verified name creation, as this call is somewhat removed from the rest of the account settings (requesting a name change vs changing the user's name immediately). I still think it makes sense to take advantage of `patchSettings` for the verified name field, however.

2021-09-15 21:01 UTC, MichaelRoytman approved these changes
Thanks for addressing my feedback!

2021-09-16 14:09 UTC, merged